# .air.toml
root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/main ./cmd/bot"
bin = "tmp/main"
full_bin = "./tmp/main"
include_ext = ["go", "yaml"]
exclude_dir = ["tmp", "vendor", "data"]
include_dir = []
exclude_file = []
delay = 1000
stop_on_error = true
log = "air.log"

[log]
time = true

[color]
main = "yellow"
watcher = "cyan"
build = "green"
runner = "magenta"

[misc]
clean_on_exit = true 